### ISSUE TITLE
Server Enrollment and /gentei check not working

### ISSUE THREAD

**Issue by eric40325** [member-gentei/member-gentei#384]
After adding a YouTube channel in the Server Enrollment section on the website, clicking "Save YouTube Channels" does nothing—there’s no response, and I can’t proceed to the next step. Refreshing the page doesn’t help either.

In my Discord server, after using the /gentei-map set command, running /gentei info confirms that the mapping was successful. However, running /gentei check only returns the message:

"This server has not configured memberships yet or has paused membership management. Please be discreet until server moderation announces something!"

This issue has persisted for at least a week.

**Comment by chirpychapa** [comment]
it still going until now, i have tried so many times and waited but nothing's happening

**Comment by ollieegan** [comment]
Also having this problem with server enrolment, cannot add new YouTube channel after inputting URL. "Save YouTube Channels" button does nothing and can't proceed to next step.

**Comment by mark-ignacio** [comment]
This should now be fixed by https://github.com/member-gentei/member-gentei/commit/d02c039e0dea9367f99e20c201bbc84665cb76e2 and https://github.com/member-gentei/member-gentei/commit/f7e60bcff7b3e073840bdedc2c5681f20f0f6ce2

**Comment by ChiyoChiyori** [comment]
![Image](https://github.com/user-attachments/assets/1b9ed6d0-456d-4748-b7ae-88a7c514b06c)
It’s still unable to save and the save button does nothing
